%net = alexnet;
full_range = 1:size(val_table,1);
validation_range = 1:100:99e3;
full_range(validation_range) = [];
validation_table = val_table(validation_range,:);
train_table = val_table(full_range,:);


layers= [ net.Layers(1:end-3)
        fullyConnectedLayer(1)
        regressionLayer];
options = trainingOptions('sgdm',...
    'InitialLearnRate',5e-4,...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropFactor',0.1,...
    'LearnRateDropPeriod',50,...
    'MaxEpochs',200,...
    'Shuffle','every-epoch',...
    'ValidationData', validation_table,...
    'ValidationPatience',inf,...
    'ValidationFrequency',1000,...
    'Verbose',true,...
    'Plots','training-progress',...
    'MiniBatchSize', 128,...
    'CheckpointPath' , 'checkpoints'); %64 ->16 for 1024 imgs
netXfer = trainNetwork(train_table,net.Layers,options);